# Generated by Django 3.2.4 on 2021-06-13 17:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('uploaded_time', models.DateField(auto_now_add=True)),
                ('file_path', models.FileField(upload_to='music')),
            ],
        ),
    ]
